

	// auto generated by build.rs
	
	pub const NAME: &str = "grc";
	pub const VERSION: &str = "1.3.0";
	pub const AUTHOR: &str = "sdttttt <sdttttt@outlook.com>";
	pub const DESCRIPTION: &str = "Similar to git-cz, gcr will help you to provide a better Git experience.";
	
	